/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[nickName]` 
  * @property `[customName]` 
  * @property `[gender]` 
  * @property `[avatarUrl]` 
  * @property `[language]` 
  * @property `[city]` 
  * @property `[province]` 
  * @property `[country]` 
  * @property `[customAvatarUrl]` 
  */
export interface Data6 {
  'nickName'?: string;
  'customName'?: string;
  'gender'?: number;
  'avatarUrl'?: string;
  'language'?: string;
  'city'?: string;
  'province'?: string;
  'country'?: string;
  'customAvatarUrl'?: string;
}

