/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ajax, { AjaxPromise, ExtraFetchParams } from '@ajax'
import * as models from '../model/models'

/* tslint:disable:no-unused-variable member-ordering object-literal-shorthand */

export class DefaultApi {
  protected $basePath = ''.replace(/\/$/, '')

  public constructor(basePath?: string) {
    if (basePath !== undefined) {
      this.$basePath = basePath.replace(/\/$/, '')
    }
  }

  /**
   *
   * @summary


   * @param opt ajax config
   * @returns {}
   */
  public apiUserGet = (opt?: ExtraFetchParams): AjaxPromise<{}> => {
    const url = this.$basePath + '/api/user'
    const p: any = {}
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
}

export default new DefaultApi()
