/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ajax, { AjaxPromise, ExtraFetchParams } from '@ajax'
import * as models from '../model/models'

/* tslint:disable:no-unused-variable member-ordering object-literal-shorthand */

/**
  * @description apiSaleWallIdGet参数
  * @property `id` 请求参数 id
  */
export interface ParamsapiSaleWallIdGet {
  // pathParams
  /**
   * 请求参数 id
   */
  id: string;
}
/**
  * @description apiSaleWallLikeIdPut参数
  * @property `id` 请求参数 id
  */
export interface ParamsapiSaleWallLikeIdPut {
  // pathParams
  /**
   * 请求参数 id
   */
  id: string;
}
/**
  * @description apiSaleWallListGet参数
  * @property `[pageNum]` 分页页码
  * @property `[pageSize]` 每页数量
  */
export interface ParamsapiSaleWallListGet {
  // queryParams
  /**
   * 分页页码
   */
  pageNum?: string;
  /**
   * 每页数量
   */
  pageSize?: string;
}
/**
  * @description apiSaleWallListLikeGet参数
  * @property `[pageNum]` 分页页码
  * @property `[pageSize]` 每页数量
  * @property `[id]` 请求参数 id
  */
export interface ParamsapiSaleWallListLikeGet {
  // queryParams
  /**
   * 分页页码
   */
  pageNum?: string;
  /**
   * 每页数量
   */
  pageSize?: string;
  /**
   * 请求参数 id
   */
  id?: string;
}
/**
  * @description apiSaleWallListPublishGet参数
  * @property `[pageNum]` 分页页码
  * @property `[pageSize]` 每页数量
  * @property `[id]` 请求参数 id
  */
export interface ParamsapiSaleWallListPublishGet {
  // queryParams
  /**
   * 分页页码
   */
  pageNum?: string;
  /**
   * 每页数量
   */
  pageSize?: string;
  /**
   * 请求参数 id
   */
  id?: string;
}
/**
  * request body
  */
export type ParamsBodyapiSaleWallPost = models.Data4
/**
  * @description apiSaleWallSearchGet参数
  * @property `[pageNum]` 分页页码
  * @property `[pageSize]` 每页数量
  * @property `[keyword]` 关键字
  */
export interface ParamsapiSaleWallSearchGet {
  // queryParams
  /**
   * 分页页码
   */
  pageNum?: string;
  /**
   * 每页数量
   */
  pageSize?: string;
  /**
   * 关键字
   */
  keyword?: string;
}

export class SaleWallApi {
  protected $basePath = ''.replace(/\/$/, '')

  public constructor(basePath?: string) {
    if (basePath !== undefined) {
      this.$basePath = basePath.replace(/\/$/, '')
    }
  }

  /**
   * 获取卖舍友详情
   * @summary 获取卖舍友详情
   * @param params ParamsapiSaleWallIdGet
   
   * @param opt ajax config
   * @returns models.InlineResponse2007
   */
  public apiSaleWallIdGet = (
    params: ParamsapiSaleWallIdGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2007>  => {
    const {
    id,
} = params
    const url = this.$basePath + `/api/sale-wall/${id}`
    const p: any = {}
    ajax.check(params.id, 'id')
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
  /**
   * 点赞/取消 卖舍友
   * @summary 点赞/取消 卖舍友
   * @param params ParamsapiSaleWallLikeIdPut
   
   * @param opt ajax config
   * @returns models.InlineResponse200
   */
  public apiSaleWallLikeIdPut = (
    params: ParamsapiSaleWallLikeIdPut,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse200>  => {
    const {
    id,
} = params
    const url = this.$basePath + `/api/sale-wall/like/${id}`
    const p: any = {}
    ajax.check(params.id, 'id')
    return ajax.ajax({
      ...opt,
      method: 'PUT',
      url,
      ...p
    })
  }
  /**
   * 获取卖舍友列表
   * @summary 获取卖舍友列表
   * @param params ParamsapiSaleWallListGet
   
   * @param opt ajax config
   * @returns models.InlineResponse2006
   */
  public apiSaleWallListGet = (
    params: ParamsapiSaleWallListGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2006>  => {
    const url = this.$basePath + '/api/sale-wall/list'
    const p: any = {}
    p.query = {}
    if ('pageNum' in params) p.query.pageNum = params.pageNum
    if ('pageSize' in params) p.query.pageSize = params.pageSize
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
  /**
   * 获取用户点赞的卖舍友列表
   * @summary 获取用户点赞的卖舍友列表
   * @param params ParamsapiSaleWallListLikeGet
   
   * @param opt ajax config
   * @returns models.InlineResponse2006
   */
  public apiSaleWallListLikeGet = (
    params: ParamsapiSaleWallListLikeGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2006>  => {
    const url = this.$basePath + '/api/sale-wall/list/like'
    const p: any = {}
    p.query = {}
    if ('pageNum' in params) p.query.pageNum = params.pageNum
    if ('pageSize' in params) p.query.pageSize = params.pageSize
    if ('id' in params) p.query.id = params.id
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
  /**
   * 获取用户发布的卖舍友列表
   * @summary 获取用户发布的卖舍友列表
   * @param params ParamsapiSaleWallListPublishGet
   
   * @param opt ajax config
   * @returns models.InlineResponse2006
   */
  public apiSaleWallListPublishGet = (
    params: ParamsapiSaleWallListPublishGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2006>  => {
    const url = this.$basePath + '/api/sale-wall/list/publish'
    const p: any = {}
    p.query = {}
    if ('pageNum' in params) p.query.pageNum = params.pageNum
    if ('pageSize' in params) p.query.pageSize = params.pageSize
    if ('id' in params) p.query.id = params.id
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
  /**
   * 新建卖舍友
   * @summary 新建卖舍友
   
   * @param data: ParamsBodyapiSaleWallPost// request body
   * @param opt ajax config
   * @returns models.InlineResponse2008
   */
  public apiSaleWallPost = (
    
    data: ParamsBodyapiSaleWallPost,opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2008>  => {
    const url = this.$basePath + '/api/sale-wall'
    const p: any = {}
    p.data = data
    return ajax.ajax({
      ...opt,
      method: 'POST',
      url,
      ...p
    })
  }
  /**
   * 根据关键字模糊搜索
   * @summary 根据关键字模糊搜索
   * @param params ParamsapiSaleWallSearchGet
   
   * @param opt ajax config
   * @returns models.InlineResponse2006
   */
  public apiSaleWallSearchGet = (
    params: ParamsapiSaleWallSearchGet,
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2006>  => {
    const url = this.$basePath + '/api/sale-wall/search'
    const p: any = {}
    p.query = {}
    if ('pageNum' in params) p.query.pageNum = params.pageNum
    if ('pageSize' in params) p.query.pageSize = params.pageSize
    if ('keyword' in params) p.query.keyword = params.keyword
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
}

export default new SaleWallApi()