/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import ajax, { AjaxPromise, ExtraFetchParams } from '@ajax'
import * as models from '../model/models'

/* tslint:disable:no-unused-variable member-ordering object-literal-shorthand */

/**
  * request body
  */
export type ParamsBodyapiUserPut = models.Data5
/**
  * request body
  */
export type ParamsBodyapiUserWxAuthPost = models.Data6
/**
  * request body
  */
export type ParamsBodyapiUserWxLoginPost = models.Data7

export class UserApi {
  protected $basePath = ''.replace(/\/$/, '')

  public constructor(basePath?: string) {
    if (basePath !== undefined) {
      this.$basePath = basePath.replace(/\/$/, '')
    }
  }

  /**
   * 获取用户信息
   * @summary 获取用户信息
   
   
   * @param opt ajax config
   * @returns models.InlineResponse2009
   */
  public apiUserGet = (
    
    opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2009>  => {
    const url = this.$basePath + '/api/user'
    const p: any = {}
    return ajax.ajax({
      ...opt,
      method: 'GET',
      url,
      ...p
    })
  }
  /**
   * 更新用户信息
   * @summary 更新用户信息
   
   * @param data: ParamsBodyapiUserPut// request body
   * @param opt ajax config
   * @returns models.InlineResponse2009
   */
  public apiUserPut = (
    
    data: ParamsBodyapiUserPut,opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2009>  => {
    const url = this.$basePath + '/api/user'
    const p: any = {}
    p.data = data
    return ajax.ajax({
      ...opt,
      method: 'PUT',
      url,
      ...p
    })
  }
  /**
   * 微信鉴权接口
   * @summary 微信鉴权接口
   
   * @param data: ParamsBodyapiUserWxAuthPost// request body
   * @param opt ajax config
   * @returns models.InlineResponse2009
   */
  public apiUserWxAuthPost = (
    
    data: ParamsBodyapiUserWxAuthPost,opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2009>  => {
    const url = this.$basePath + '/api/user/wx/auth'
    const p: any = {}
    p.data = data
    return ajax.ajax({
      ...opt,
      method: 'POST',
      url,
      ...p
    })
  }
  /**
   * 微信登录接口
   * @summary 微信登录接口
   
   * @param data: ParamsBodyapiUserWxLoginPost// request body
   * @param opt ajax config
   * @returns models.InlineResponse2009
   */
  public apiUserWxLoginPost = (
    
    data: ParamsBodyapiUserWxLoginPost,opt?: ExtraFetchParams
  ) : AjaxPromise<models.InlineResponse2009>  => {
    const url = this.$basePath + '/api/user/wx/login'
    const p: any = {}
    p.data = data
    return ajax.ajax({
      ...opt,
      method: 'POST',
      url,
      ...p
    })
  }
}

export default new UserApi()