export { default as Loading } from './loading'
export { default as withLoading } from './loading/withLoading'
export { default as CaptchaModal } from './captcha-modal'
export { default as Wxml2canvas } from './wxml2canvas'
export { default as Cropper } from './cropper'
export { default as withShare } from './@with-share'
