/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[imageDataA]` 图片A
  * @property `[imageDataB]` 图片B
  */
export interface Data {
  /**
   * 图片A
   */
  'imageDataA'?: string;
  /**
   * 图片B
   */
  'imageDataB'?: string;
}

