/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[encryptedData]` 微信解密参数 encryptedData
  * @property `[iv]` 微信解密参数 iv
  */
export interface Data8 {
  /**
   * 微信解密参数 encryptedData
   */
  'encryptedData'?: string;
  /**
   * 微信解密参数 iv
   */
  'iv'?: string;
}

