/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[name]` 姓名
  * @property `[gender]` 
  * @property `[major]` 主修专业
  * @property `[description]` 描述
  * @property `[content]` 内容
  * @property `[photos]` 图片列表
  */
export interface Data2 {
  /**
   * 姓名
   */
  'name'?: string;
  'gender'?: number;
  /**
   * 主修专业
   */
  'major'?: string;
  /**
   * 描述
   */
  'description'?: string;
  /**
   * 内容
   */
  'content'?: string;
  /**
   * 图片列表
   */
  'photos'?: Array<string>;
}

