/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[height]` 图片高度
  * @property `[width]` 图片宽度
  * @property `[type]` 图片类型
  * @property `[url]` 图片 url
  * @property `[client]` bucket client name
  */
export interface Data3 {
  /**
   * 图片高度
   */
  'height'?: number;
  /**
   * 图片宽度
   */
  'width'?: number;
  /**
   * 图片类型
   */
  'type'?: string;
  /**
   * 图片 url
   */
  'url'?: string;
  /**
   * bucket client name
   */
  'client'?: string;
}

