/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `_id` user id
  * @property `createdAt` 创建时间
  * @property `[userInfo]` 
  * @property `commentLikeCount` 评论点赞数量
  * @property `commentPublishCount` 评论发布数量
  * @property `brickLikeCount` 表白墙点赞数量
  * @property `brickCollectCount` 表白墙收藏数量
  * @property `brickPublishCount` 表白墙发布数量
  * @property `mateLikeCount` 卖舍友点赞数量
  * @property `mateCollectCount` 卖舍友收藏数量
  * @property `matePublishCount` 卖舍友发布数量
  * @property `[tags]` 
  */
export interface InlineResponse2001From {
  /**
   * user id
   */
  '_id': string;
  /**
   * 创建时间
   */
  'createdAt': number;
  'userInfo'?: models.InlineResponse2001FromUserInfo;
  /**
   * 评论点赞数量
   */
  'commentLikeCount': number;
  /**
   * 评论发布数量
   */
  'commentPublishCount': number;
  /**
   * 表白墙点赞数量
   */
  'brickLikeCount': number;
  /**
   * 表白墙收藏数量
   */
  'brickCollectCount': number;
  /**
   * 表白墙发布数量
   */
  'brickPublishCount': number;
  /**
   * 卖舍友点赞数量
   */
  'mateLikeCount': number;
  /**
   * 卖舍友收藏数量
   */
  'mateCollectCount': number;
  /**
   * 卖舍友发布数量
   */
  'matePublishCount': number;
  'tags'?: Array<string>;
}

