/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `confidence` 比对相似度
  * @property `qualityScoreA` 图片A质量
  * @property `qualityScoreB` 图片B质量
  */
export interface InlineResponse2004Result {
  /**
   * 比对相似度
   */
  'confidence': string;
  /**
   * 图片A质量
   */
  'qualityScoreA': string;
  /**
   * 图片B质量
   */
  'qualityScoreB': string;
}

