/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `_id` user id
  * @property `[userInfo]` 
  */
export interface InlineResponse2001From {
  /**
   * user id
   */
  '_id': string;
  'userInfo'?: models.InlineResponse2001FromUserInfo;
}

