/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `key` 图片 url
  * @property `status` 
  * @property `[height]` 图片高度
  * @property `[width]` 图片宽度
  * @property `[type]` 图片类型
  * @property `[bucket]` 图片 bucket
  * @property `_id` 图片 id
  */
export interface InlineResponse2002Result {
  /**
   * 图片 url
   */
  'key': string;
  'status': InlineResponse2002Result.StatusEnum;
  /**
   * 图片高度
   */
  'height'?: number;
  /**
   * 图片宽度
   */
  'width'?: number;
  /**
   * 图片类型
   */
  'type'?: string;
  /**
   * 图片 bucket
   */
  'bucket'?: string;
  /**
   * 图片 id
   */
  '_id': string;
}

export namespace InlineResponse2002Result {
  export enum StatusEnum {
    _0 = '0' as any,
    _1 = '1' as any,
    _2 = '2' as any
  }
}
