/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `createdAt` 创建时间
  * @property `updatedAt` 更新时间
  * @property `_id` 表白墙id
  * @property `isPublisher` 是否是发布者
  * @property `isLike` 是否点赞
  * @property `likeCount` 点赞数
  * @property `isCollect` 是否收藏
  * @property `collectCount` 收藏数量
  * @property `[publisher]` 
  * @property `name` 姓名
  * @property `gender` 
  * @property `major` 主修专业
  * @property `description` 描述
  * @property `[content]` 内容
  * @property `[photos]` 图片列表
  * @property `isDelete` 是否删除
  */
export interface InlineResponse2004Result {
  /**
   * 创建时间
   */
  'createdAt': number;
  /**
   * 更新时间
   */
  'updatedAt': number;
  /**
   * 表白墙id
   */
  '_id': string;
  /**
   * 是否是发布者
   */
  'isPublisher': boolean;
  /**
   * 是否点赞
   */
  'isLike': boolean;
  /**
   * 点赞数
   */
  'likeCount': number;
  /**
   * 是否收藏
   */
  'isCollect': boolean;
  /**
   * 收藏数量
   */
  'collectCount': number;
  'publisher'?: models.InlineResponse2004Publisher;
  /**
   * 姓名
   */
  'name': string;
  'gender': number;
  /**
   * 主修专业
   */
  'major': string;
  /**
   * 描述
   */
  'description': string;
  /**
   * 内容
   */
  'content'?: string;
  /**
   * 图片列表
   */
  'photos'?: Array<models.InlineResponse2003Photo>;
  /**
   * 是否删除
   */
  'isDelete': boolean;
}

