/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[photo]` 
  * @property `brickId` brickId
  * @property `metaId` brickId
  * @property `commentId` brickId
  */
export interface InlineResponse2003Ext {
  'photo'?: models.InlineResponse2003ExtPhoto;
  /**
   * brickId
   */
  'brickId': string;
  /**
   * brickId
   */
  'metaId': string;
  /**
   * brickId
   */
  'commentId': string;
}

