/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `createdAt` 创建时间
  * @property `updatedAt` 更新时间
  * @property `_id` 消息 id
  * @property `to` 消息接收人
  * @property `from` 消息发送人
  * @property `content` 内容
  * @property `[photo]` 
  */
export interface InlineResponse2003Result {
  /**
   * 创建时间
   */
  'createdAt': number;
  /**
   * 更新时间
   */
  'updatedAt': number;
  /**
   * 消息 id
   */
  '_id': string;
  /**
   * 消息接收人
   */
  'to': string;
  /**
   * 消息发送人
   */
  'from': string;
  /**
   * 内容
   */
  'content': string;
  'photo'?: models.InlineResponse2003Photo;
}

