/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `[from]` 
  * @property `[to]` 
  * @property `type` 评论类型
  * @property `[brickId]` 若评论表白墙，需要表白墙 id
  * @property `[mateId]` 若评论卖舍友，需要卖舍友 id
  * @property `[commentId]` 评论回复评论，需要评论 id
  * @property `content` 评论内容
  * @property `createdAt` 创建时间
  * @property `updatedAt` 更新时间
  * @property `_id` id
  */
export interface InlineResponse2001Result {
  'from'?: models.InlineResponse2001From;
  'to'?: models.InlineResponse2001From;
  /**
   * 评论类型
   */
  'type': number;
  /**
   * 若评论表白墙，需要表白墙 id
   */
  'brickId'?: string;
  /**
   * 若评论卖舍友，需要卖舍友 id
   */
  'mateId'?: string;
  /**
   * 评论回复评论，需要评论 id
   */
  'commentId'?: string;
  /**
   * 评论内容
   */
  'content': string;
  /**
   * 创建时间
   */
  'createdAt': number;
  /**
   * 更新时间
   */
  'updatedAt': number;
  /**
   * id
   */
  '_id': string;
}

