/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `createdAt` 创建时间
  * @property `updatedAt` 更新时间
  * @property `_id` id
  * @property `key` key
  * @property `config` 配置
  */
export interface InlineResponse2002Result {
  /**
   * 创建时间
   */
  'createdAt': number;
  /**
   * 更新时间
   */
  'updatedAt': number;
  /**
   * id
   */
  '_id': string;
  /**
   * key
   */
  'key': string;
  /**
   * 配置
   */
  'config': any;
}

