/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `createdAt` 创建时间
  * @property `updatedAt` 更新时间
  * @property `_id` 表白墙id
  * @property `isPublisher` 是否是发布者
  * @property `isLike` 是否点赞
  * @property `likeCount` 点赞数
  * @property `isCollect` 是否收藏
  * @property `collectCount` 收藏数量
  * @property `[publisher]` 
  * @property `to` wall id
  * @property `tel` 手机号
  * @property `content` 内容
  * @property `[photos]` 图片列表
  * @property `isDelete` 是否删除
  * @property `commentCount` 评论数
  * @property `[hotComments]` 热门评论
  */
export interface InlineResponse20012Result {
  /**
   * 创建时间
   */
  'createdAt': number;
  /**
   * 更新时间
   */
  'updatedAt': number;
  /**
   * 表白墙id
   */
  '_id': string;
  /**
   * 是否是发布者
   */
  'isPublisher': boolean;
  /**
   * 是否点赞
   */
  'isLike': boolean;
  /**
   * 点赞数
   */
  'likeCount': number;
  /**
   * 是否收藏
   */
  'isCollect': boolean;
  /**
   * 收藏数量
   */
  'collectCount': number;
  'publisher'?: models.InlineResponse2001From;
  /**
   * wall id
   */
  'to': string;
  /**
   * 手机号
   */
  'tel': string;
  /**
   * 内容
   */
  'content': string;
  /**
   * 图片列表
   */
  'photos'?: Array<models.InlineResponse2001FromUserInfoCustomAvatarUrl>;
  /**
   * 是否删除
   */
  'isDelete': boolean;
  /**
   * 评论数
   */
  'commentCount': number;
  /**
   * 热门评论
   */
  'hotComments'?: Array<models.InlineResponse2001ReplyComment>;
}

