/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models'

/**
  * @property `downloadType` 下载类型
  * @property `url` 下载地址
  * @property `[password]` 下载密码
  * @property `[decompressionPassword]` 解压密码
  */
export interface InlineResponse2006DownloadUrl {
  /**
   * 下载类型
   */
  'downloadType': number;
  /**
   * 下载地址
   */
  'url': string;
  /**
   * 下载密码
   */
  'password'?: string;
  /**
   * 解压密码
   */
  'decompressionPassword'?: string;
}

